### ISSUE TITLE
Referencia pontokat tartalmazó json állomány feldolgozása

### ISSUE THREAD

**Issue by Eurioin** [SzFMV2020-Tavasz/AutomatedCar-A#102]
A viszonyítási pontokat tartalmazó json állomány felolvasás, és példányosítása a kódban.

**Comment by pintergreg** [comment]
Ki ne találjátok, hogy magatok parse-oljátok stringből a JSON-t...
https://github.com/SzFMV2020-Tavasz/AutomatedCar-A/pull/101#discussion_r389549002
