### ISSUE TITLE
Nullreference a mintateszt futtatása során

### ISSUE THREAD

**Issue by Eurioin** [SzFMV2020-Tavasz/AutomatedCar-A#13]
Alap tesztelés során nullreference-t dob.

**Comment by pintergreg** [comment]
Ez valójában két issue, ennek megfelelően szét is bontom.

**Comment by pintergreg** [comment]
A hibát az okozta, hogy a JUnit 4-es `@Before` annotáció maradt bent, miközben már JUnit 5-öt használunk, így az nem végzi el a dolgát. JUnit 5-ben a `@BeforeEach` annotáció jelenti ugyanazt.

Ennek javításával a teszt működik. Hogy ez eddig hogy nem tűnt fel, azt nem tudom.

Ref:
 - https://howtodoinjava.com/junit5/junit-5-vs-junit-4/
 - https://www.baeldung.com/junit-5-migration
