### ISSUE TITLE
Billentyű kiosztás

### ISSUE THREAD

**Issue by bodapeter** [SzFMV2020-Tavasz/AutomatedCar-A#16]
s-fék
w-gáz
a-bal kanyar
d-jobb kanyar
q-bal index
e-jobb index
k-lefele váltás
l-felfele váltás
i-tempomat le
o-tempomat fel
ctr+0 - debug mod
t-tempomat
(edit by Benji)
j- lane Keeping Assistant ki/be
p - Pakring Pilot ki/be
u - követi távolság növelés

**Comment by chowder23** [comment]
Szerintem így jó lesz

**Comment by pintergreg** [comment]
Kell még egy Lane Keeping Assistant és egy Parking Pilot kapcsoló.

**Comment by bodapeter** [comment]
ki lett osztva az is billentyűre, szerintem doneolható ez az issu,mert sokkal több issu lérte lett hozva ez alapján az issu alapján @chowder23
