### ISSUE TITLE
Billentyű beolvasó osztály

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#17]
egy osztály ami a billentyűk lenyomását és felengedését vizsgálja és a megfelelő billentyűk leütésénél a megfelelő metódust hívja meg és ugyan így a billentyű felengedésénél is amennyiben szükséges. #16 alapján
Lenyomást figyelni kell:
- W #31 
- S #33 
- D #38 
- A #35 
- Q #39 
- E #40 
- K #41 
- L #42 
- I #43 
- O (betű) #44 
- P #48 
- CTRL #46 
- 0 (nulla) #46 
- J #47 
- P #48 
- U #58 

Felengedést figyelni kell:
- W #32 
- S #34 
- D #37 
- A #36

**Comment by pintergreg** [comment]
Ez nem egy user story!
