### ISSUE TITLE
Billentyűz feldolgozó osztály

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#18]
Kell egy osztály ami kapja az inputot a billentyűzet beolvasó osztálytól és azzal végez egy kis számolást és azt felrakja a bus-ra illetve az interfész osztály-nak 
Szükséges adatok:
 Melyik billentyű lenyomása mit jelentsen (van rá task)
Adott billentyű meddig volt lenyomva(lehet át kéne rakni a beolvasó osztályba)
Belső adatok állítása:
  -Gáz mértéke (0-100) #82 
  -Fék mértéke (0-100) #82 
  -Kormány állása (0-180, 90 a közép) #87 
  -Index helyzete (Jobbra,kikapcsolva,Balra)
  -Váltó állása (P.N.D.R) #86 
  -Követési távolság(körkörösen 0.8/1.0/1.2/1.4 másodperc) #70 
  -Tempomat (30-160, 10-esével lépkedve) #70

**Comment by pintergreg** [comment]
Ez a task milyen relációban áll a #17-el? Nem teljesen látom a beolvasás és a feldolgozás közötti ugrást.

**Comment by chowder23** [comment]
Úgy gondoltam, hogy a másik osztály csak azért felelős, hogy megmondja melyik billentyű van éppen lenyomva és értesítést küld, hogy mikor van felengedve. Ez az osztály arról dönt, hogy mi történjen, ha egyáltalán történik valami, egy billentyű leütésekor. 
Pl: A másik osztály értesítést küld, hogy lenyomták a W gombot, ez az osztály pedig addig növeli a gázpedál lenyomottságát amíg nem kap értesítést, hogy felengedték a gombot.
