### ISSUE TITLE
GUI megrajzolása

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#19]
Meg kell rajzolni az egész GUI-t amin elég sok adatnak kell szerepelnie. Sokat mi magunk állítunk elő (pl index) de sokat a bus-ról kapunk más csapatoktól.

A megjelenítéshez van egy kép a Sprint1-es user storyban

**Comment by ersok** [comment]
- [ ] adatok feldolgozása a buszról

- [ ] kinézet véglegesítése
