### ISSUE TITLE
Mindenkinek megvan a fejlesztői környezete

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#20]
- [x] Benji
- [x] Peti
- [x] Gergő
- [x] Máté

https://www.jetbrains.com/idea/   <-- ajánlott

**Comment by pintergreg** [comment]
@ersok @bodapeter @cobhc776 Mi hátráltat a titeket a működő fejlesztőkörnyezet kialakításában?
