### ISSUE TITLE
Debug mode lekérdezése 

### ISSUE THREAD

**Issue by ArchiCat** [SzFMV2020-Tavasz/AutomatedCar-A#26]
Definition of Done

- [x]  Debug mode beállítás levétele virtualfuncionbusról

- [x] Debug mode beállítások továbbadása DisplayObject felé

**Comment by konyarilaszlo** [comment]
Debug módot hozzáadtam. A task második fele még nem tudott elkészülni mert nagyon hiányos még a kód.

**Comment by ArchiCat** [comment]
A Debug mode beállítások továbbadásához az interfész a DisplayWorld classban elkészült. További összekötés a párhuzamos csapatok munkájának függvényében készül majd a következő sprintekben,

**Comment by pintergreg** [comment]
@ArchiCat Erre én lehet, hogy nyitva hagynék egy issue-t, akár ezt. Teljesen értem, hogy külső függőség, de ettől még valahol ezt lehet vezetni, hogy nem teljesen van kész, pontosabban, hogy a kapcsolás nincs meg.

Ha pedig interfész szinten megvan az egész, akkor a HMI csapatnak felvenni egy issue-t, hogy hívják meg a debug billentyű feldolgozásakor.
