### ISSUE TITLE
Szenzorháromszögek megjelenítése 

### ISSUE THREAD

**Issue by ArchiCat** [SzFMV2020-Tavasz/AutomatedCar-A#28]
Definition of Done
- [x] Az egyes szenzorok külön-külön felkapcsolhatóak
- [x] A szenzorok színei egyeznek a silabusz szineivel

**Comment by pintergreg** [comment]
Mit jelent az elemlista?

**Comment by ArchiCat** [comment]
> Mit jelent az elemlista?

Többféle szenzor is van, a lista adja meg, hogy melyiknél rajzoljuk ki a háromszöget.

**Comment by pintergreg** [comment]
Oké, akkor legyen definiálva, hogy mi a lista típusa.
