### ISSUE TITLE
InputPacket interfész a powertrain csapatnak

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#29]
Kell egy interfész ami VFB-n lévő pacekhez ami tartalmazza a power train számára szükséges adatokat.
Adatok:
- gázpedál állása int
- fékpedál állása int
- kormány állása int
- váltókar állása enum

**Comment by bodapeter** [comment]
PowerTrain csapat kérésére csak bizonyos adatokat adunk tovább. Interface modósítása szükséges.
