### ISSUE TITLE
InputPacket osztály a powertrain számára

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#30]
A #29 interfészt megvalósító osztály
gázpedál állása int (0-100)
fékpedál állása int (0-100)
kormány állása int (-180-180)
váltókar állása enum (P-R-N-D)

**Comment by bodapeter** [comment]
#29 miatt ez is visszarakva in Progress

**Comment by bodapeter** [comment]
Powertrain team ha ellenörizte a kellő adatokat akkor done. @varszegimarcell
