### ISSUE TITLE
Nyomatékszámítás Üresben

### ISSUE THREAD

**Issue by aether-fox** [SzFMV2020-Tavasz/AutomatedCar-A#52]
**Covered in**: #188

Előfeltétel: [Egyszerű Nyomatékszámítás](https://github.com/SzFMV2020-Tavasz/AutomatedCar-A/issues/50)

Nyomaték számítása üres váltóállásban. Nyomaték nulla? Vagy van értelme, hogy csökken a nyomaték ha épp leváltottak valamiből?

**Comment by varszegimarcell** [comment]
Szerintem ha D-ből tették ki üresbe az autót (vagy R-ből) akkor a nyomatéknak le kellene csökkennie 0-ra, elvégre ilyenkor nincs hajtva az autó. Természetesen a gáz adása továbbra is növeli a fordulatszámot, de a nyomaték konstans 0 marad.
