### ISSUE TITLE
Repó Leklónozása Lokálba

### ISSUE THREAD

**Issue by AbyssPrince** [SzFMV2020-Tavasz/AutomatedCar-A#56]
Mindenki klónozza le valamilyen módon a repository-t:
- külső git verziókezelő programmal, vagy
- IntelliJ IDEA-ban import project from version control

- [x] Péter
- [x] Kevin
- [x] Marcell
- [x] Dávid

**Comment by Szajkop** [comment]
Something is fucky
[http://prntscr.com/r86juq](url)

**Comment by Szajkop** [comment]
> 
> 
> Something is fucky
> [link](http://prntscr.com/r86juq)

Megoldás:
maven clean
maven install

build
