### ISSUE TITLE
Rendszer Komponens Hozzáadása

### ISSUE THREAD

**Issue by AbyssPrince** [SzFMV2020-Tavasz/AutomatedCar-A#59]
Rendszer komponens hozzáadása.

Tasks:
- [x] komponens létrehozása saját branch-en (#59-add-system-component)
- [x] PowerTrain osztály létrehozása
- [x] PowerTrain példány integrálása az AutomatedCar osztályba

**Comment by varszegimarcell** [comment]
move it to done
