### ISSUE TITLE
Egyeztetés a power train csapattal a GUI-hoz szükséges adatok megkapásáról

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#60]
Meg kell beszélni a power train csapattal, hogy a GUI-hoz süzkséges adatok:
- aktuális sebesség
- aktuális fordulatszám

**Comment by varszegimarcell** [comment]
Sziasztok! A powertrain csapat egyik tagja vagyok. 

Valószínűleg ezeket az adatokat rendkívül egyszerűen fogjátok megkapni:

sebesség: speed, integer - sebesség Km/H mértékegységben
fordulatszám: RPM, integer - fordulatszám fordulat / perc mértékegységben

Természetesen a változók nevei nincsenek kőbe vésve, illetve egy interfészt fogunk biztosítani az adatok eléréséhez.

**Comment by varszegimarcell** [comment]
Sziasztok! A powertrain csapat egyik tagja vagyok. 

Valószínűleg ezeket az adatokat rendkívül egyszerűen fogjátok megkapni:

sebesség: speed, integer - sebesség Km/H mértékegységben
fordulatszám: RPM, integer - fordulatszám fordulat / perc mértékegységben

Természetesen a változók nevei nincsenek kőbe vésve, illetve egy interfészt fogunk biztosítani az adatok eléréséhez.

**Comment by chowder23** [comment]
Szia. Rendben van, köszi. @ersok dolgozik nálunk a GUI-n. Csak ezért pingeltelek, hogy ha esetleg kellenek ezek az adatok
