### ISSUE TITLE
Egyeztetés a visualization csapattal aGUI-hoz szükséges adatok megkapásáról

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#61]
Meg kell beszélni a visualization csoportal, hogy a GUI-hoz hogyan kapjuk meg:
- x,y koordináta
- utolsó tábla

**Comment by ersok** [comment]
Milyen alakban kapjuk meg ezen adatokat? @SzFMV2020-Tavasz/team-a4

**Comment by ArchiCat** [comment]
> Milyen alakban kapjuk meg ezen adatokat? @SzFMV2020-Tavasz/team-a4

Ezt az órán már tisztáztuk. Tőlünk ilyen adatot nem kaptok. Ebben a sprintben mi nem állítunk elő semmilyen adatot, csak megjelenítünk.
