### ISSUE TITLE
Váltó viselkedés modellezése

### ISSUE THREAD

**Issue by varszegimarcell** [SzFMV2020-Tavasz/AutomatedCar-A#63]
Sziasztok!

Mint az autó hajtásláncáért felelős csapat, nekünk kell modelleznünk a váltó viselkedését is.

Fontos, hogy mi megkapjuk a kéréseket majd valamilyen formában. Kérés alatt például a D, illetve P, N, R gombok lenyomását értem, ami egyenértékü a váltókar átállításával. ha egy vezető vezetné az autót. Előfordulhatnak olyan szituációk, amikor például a kocsi halad D-ben ötvennel, és betenné az user P-be a kocsit. Ezt nyilván nem veszi be a valóságban egy autó.

Tételesen összeszedve:
-Realisztikus automata váltó modellezés (D-N-P-R)
-Driving fokozatszám kezelése (1-5, 6, 7 ? ezt meg kellene vitatni)
-Reverse fokozat kezelése
-Netural fokozat megfelelő kezelése

Fontos, hogy a fordulókör, illetve a nyomatékszámítás feladatok is alapjaiban függenek a váltó viselkedésétől, így először ezt le kellene tisztázni.

Várom a vitát az issue alatt ;)

Előkövetelmények:
- [x] [Interfész Pekidzsek' Létrehozása](https://github.com/SzFMV2020-Tavasz/AutomatedCar-A/issues/57) -- `TransmissionMode` enum.

**Comment by varszegimarcell** [comment]
Üdv

Elkezdek dolgozni a váltón.

**Comment by varszegimarcell** [comment]
Probléma: merge-re kell várnom, mivel van olyan interfész függőben, ami az én feladatomat érintené.

**Comment by AbyssPrince** [comment]
> Probléma: merge-re kell várnom, mivel van olyan interfész függőben, ami az én feladatomat érintené.

Beraktam a ticket-be mint előkövetelmény. A pull request él, dobjatok approve-ot és be-mertge-elem.

**Comment by varszegimarcell** [comment]
Mivel több javaslat nem jött, én hasraütésszerűen 5 fokozatú váltót fogok csinálni. (D belső állapotai.)

**Comment by pintergreg** [comment]
@varszegimarcell Bőven jó, ez egy utcai autó. (Nekünk meg teljesen mindegy, hogy 4, 5 vagy 6 fokozatú. Egyszer csináltak 7 fokozatút, bár nem tudom minek. :D)
