### ISSUE TITLE
Bejövő interfész és adatok formátuma

### ISSUE THREAD

**Issue by varszegimarcell** [SzFMV2020-Tavasz/AutomatedCar-A#64]
Sziasztok!

Megkeresést kaptunk az A1-es csapattól abban az ügyben, hogy szeretnék tisztázni milyen adatokra is lenne szükségünk pontosan, és milyen formátumban. 

Amit specifikálni kellene:
- Bejövő adatok típusa, száma, annak adattartalma
- Ezen adatok értelmezési tartományainak a tisztázása

FONTOS, hogy az A1-es csapat ezt mindenképpen szeretné mielőbb letudni, én szóban ma estét ígértem nekik, ezért a feladatot magas prioritással jelölöm meg. Az én elképzeléseimet leírom az első kommentben, szívesen várok minden jellegű ötletelést. 

Az A1-es csapat a megvitatásunk eredményeit egy Issue-ban kapja majd meg.

**Comment by varszegimarcell** [comment]
Én arra gondoltam, hogy a következőt kellene megrendelni:

Gáz, 0-100 (százalékosan értelemszerűen)
Fék, 0-100
Kormányállás, -180-180 (0 közép, negatív irány balra pozitív jobbra)
Felhasználó által utoljára kért váltóállás (karakteres, D-N-P-R)

**Comment by Szajkop** [comment]
Szerintem:

Gázpedál: 0.0-100.0 (%)
Fékpedál: 0.0-100.0 (%)
Automata váltókar állás: Drive, Neutral, Parking, Reverse (enum tipuskent)

Kormányszög meg igazából attól függ hogy a hozzátartozó trigonometriai műveletek milyen formátumban számolnak, hogy ne kelljen helyben mappelgetni az értékeket.

**Comment by varszegimarcell** [comment]
> Kormányszög meg igazából attól függ hogy a hozzátartozó trigonometriai műveletek milyen formátumban számolnak, hogy ne kelljen helyben mappelgetni az értékeket.

Na igen, ezt mindenképpen célszerűen kellene megválasztani. Átrágom délutány az irány meghatározásának matematikáját és írom hogyan lenne célszerűbb.

Természetesen a többi csapattag véleményére is kíváncsi lennék.
@Keev2n @AbyssPrince

**Comment by Keev2n** [comment]
Támogatom @Szajkop ötletét. 

Könnyebb és áttekinthetőbb lesz a kód ha nem kell át írogatni, hanem csak egyből számolni a kormányszöget.

**Comment by chowder23** [comment]
Sziasztok az A1 csapatból vagyok.
Akkor mi legyen a végleges formátum?
Gáz/fék :  double, 0.0-100.0 
Váltó: enum, Drive, Neutral, Parking, Reverse
Kormány: int, -180-180
Így jó vagy a kormánszög esetleg megnva pontosan?

**Comment by varszegimarcell** [comment]
> 
> 
> Sziasztok az A1 csapatból vagyok.
> Akkor mi legyen a végleges formátum?
> Gáz/fék : double, 0.0-100.0
> Váltó: enum, Drive, Neutral, Parking, Reverse
> Kormány: int, -180-180
> Így jó vagy a kormánszög esetleg megnva pontosan?

Szia

Szerintem tökéletes ebben a formában. Ha esetleg nekünk a matematikához majd máshogy kellene a kormányszüg, ebből eléggé könnyen át tudjuk írni a dolgokat.
