### ISSUE TITLE
Model API-k implementálása

### ISSUE THREAD

**Issue by BenjaminHun** [SzFMV2020-Tavasz/AutomatedCar-A#73]
Az interfészek implementálása a modelben lévő objektumok eléréséhez.
API 1: minden objektum átadása
API 2: csak a dinamikus objektumok átadása.
API 3: objektum átadása id alapján.
API 4: az autó objektum mozgatásához szukséges informáciok bekérése.

**Comment by pintergreg** [comment]
Ez egy elég tágan megfogalmazott issue. Milyen interfészeknek milyen objektumokat kell elérnie?

**Comment by BenjaminHun** [comment]
Rendben kibovitem azokrol az apikrol van szó amiket a táblára felrajzoltunk

2020.03.03., K 14:47 dátummal Gergő Pintér <notifications@github.com> ezt
írta:
