### ISSUE TITLE
Csapat jelentkezés

### ISSUE THREAD

**Issue by konyarilaszlo** [SzFMV2020-Tavasz/AutomatedCar-A#80]
@pintergreg A 4-es csapatba szeretnék jelentkezni.

**Comment by pintergreg** [comment]
@konyarilaszlo Ez miért tartott egy hétig?

**Comment by konyarilaszlo** [comment]
@pintergreg Sajnos nem volt korábban érkezésem rá, nagyon sűrű hetem volt. Köszönöm a meghívást!
