### ISSUE TITLE
Else ág

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#89]
https://github.com/SzFMV2020-Tavasz/AutomatedCar-A/blob/094ec8a0762bf0bb74be841fef50fcc8301683cd/src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/KeyListener.java#L97

Hiányzik az else ág

**Comment by pintergreg** [comment]
Egyrészt nem önmagában érzem ezt problémának, mármint szerintem nem ez a probléma a kóddal. Hogy fogalmazzam meg... Jelen esettben az else ág megjavítja, de nem így nevezném a problémát. 
Ugyanis az ACC-t mindig bekapcsoljátok, én kb. erre utalnék az issue elnevezésében, mivel  azt próbáljátok megvalósítani, hogy a T megnyomása esetén ha az ACC be volt kapcsolva, akkor kikapcsoljon, ha ki van kapcsolva akkor bekapcsoljon(, igaz?).

Ez az issue, ezzel a címmel és leírással szerintem inkább zaj mint hasznos tartalom, pláne ha a PR-ben ez nincs felvetve, akkor senki nem jön rá, hogy hova kapcsolódik.

Másrészt ha nem kell minden review findingból issue-t csinálni. Ha szerinted ez probléma megjelölöd review során és egy request changes-t nyomsz. Ha a finding jellege indokolja, akkor lehet belőle issue-t létrehozni.

Az accmanager-nek van egy getter-e a bekapcsoltságra (`isOn()`), és pl. C#-ban property-vel lenne valami ilyesmit írni, hogy `accmanager.status = !accmanager.status;`, tehát átbillented. A turnOn/Off olvasmányosabb, tehát egyértelműbb lehet, hogy mi történik. Ebből a szempontból nem rossz választás. A javítása tényleg egy else ág, de probélmát szerintem nem írja le kellőképpen.
