### ISSUE TITLE
Rossz hívás

### ISSUE THREAD

**Issue by chowder23** [SzFMV2020-Tavasz/AutomatedCar-A#90]
https://github.com/SzFMV2020-Tavasz/AutomatedCar-A/blob/094ec8a0762bf0bb74be841fef50fcc8301683cd/src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/KeyListener.java#L86

A KeyListener ne legyen csak KeyPrecesszor osztály meghívása

@bodapeter

**Comment by pintergreg** [comment]
@chowder23 Ez megint egy review finding?

**Comment by chowder23** [comment]
Igen. Most olvastam el a másik kommentedet is. Az a request changes dolog hogy néz ki, vagy hogya nkell alkalmazni?

**Comment by pintergreg** [comment]
@chowder23 Review-zni, dokumentált, visszakövethető módon, a GH nyújtotta eszközön keresztül nyitott Pull Requestet tudsz. Csak úgy simán a kódba bele nem.

Nektek a #69 elé régóta nyitva van, igazából te vársz review-ra, de a #77 -en biztos megtalálod fönt az add your review gombot. Ekkor kapsz egy felületet, ahol minden egyes, a PR-ben levő commit-ok által érintett fájlt egyesével át tudsz nézni, szintaxiskiemelés van természetesen és azt is látod mi változott.

A kód bármely sorához fűzhetsz kommentet mint amilyeneket ez az issue is képvisel. A teljes review eredményét 3 opcióval összegezheted: 
    - approve: mindent rendben találtál
    - comment: semleges, de van megjegyzésed
    - request changes: azt akarod, hogy kijavítsanak valamit.

A PR akkor fogadható el ha 2 approve érkezik hozzá, egyébként megakad a fejlesztés. A #69 erre kiváló példa.

Mivel a request changes megakasztja a PR elfogadását, és dokumentált visszakövethető módja a talált hibáknak, én nem ragaszkodom hozzá, hogy minden findingból issue készüljön. Az aki a PR-t nyitotta minimum kap értesítést arról, hogy valamit kifogásoltak a kódjában, de az illető taggelésével biztosra is mehetsz.

Külön issue-t én talán akkor nyitnék ha találtál valamit ami nem a PR scope-ja (hiszem a PR egy task-hoz (kéne) kapcsolódjon, így annak a scope-ja tisztázott), de egyértelműen gondot okoz(hat) így javításra szorul. Ez nem kőbe vésett szabály, @ravaszla lehet másképp fogalmazná meg, valamit a céges szokások is befolyásolhatják.

GH helpjéből:
    - https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews
