### ISSUE TITLE
Team A2 - Sprint 1 - Poligonok

### ISSUE THREAD

**Issue by Eurioin** [SzFMV2020-Tavasz/AutomatedCar-A#96]
Objektum ütközéséhez szükséges poligon létrehozása, ami nem egyezik meg a betöltendő kép széleivel.
Pl.: 
- Fa -> nem a lombkoronába ütközünk, hanem a törzsébe, de a kép még a lombnál is szélesebb.

**Comment by pintergreg** [comment]
- polinom != poligon
- az issue neve nem túl beszédes
     - A TeamA2 igazából redundáns a projekt megadása miatt, a Sprint 1 meg a milestone megadása miatt, a „Poligonok” meg nem írja le, hogy mi a feladat.
- Ez valójában függősége a #97 -nek.
    - Amíg nincsenek poligonok tartalmazást sem lehetne vizsgálni.
    - Erről írtam még a Team4 PR-jében is...

**Comment by pintergreg** [comment]
Team4 megoldotta.
